title: HaesooKimDev
description: 잡다하게 공부한 것들 업로드하는 블로그입니다.
theme: just-the-docs

url: https://haesookimdev.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
